language: go

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libglfw-dev libglew1.6-dev libxrandr-dev

install: export GOPATH=`pwd` && cd src/neato && go get -d -v && go get -d -v "launchpad.net/gocheck" && go build -v

script: go test -v
